### ISSUE TITLE
Add Docker support for the API

### ISSUE THREAD

**Issue by matthiashermsen** [matthiashermsen/dotnet-backend#1]
## Description
Add Docker to the API project.

## Expected solution
Run the API in a Docker container.

## Considered alternatives
N/A

## Additional context
N/A

**Comment by matthiashermsen** [comment]
Proposed files:

**Dockerfile**

```
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet
WORKDIR /app
EXPOSE 443 80
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet", "Rest.dll" ]
```

**docker-compose**

```yml
version: '3.9'
services:
  api:
    ports:
      - '443:443'
      - '80:80'
    image: api
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
```

**.dockerignore**

```
.git
Dockerfile
bin/
obj/
```
